force-app/main/default/objects/BoredActivity__c/BoredActivity__c.object-meta.xml
<CustomObject>
    <label>BoredActivity</label>
    <nameField>
        <displayFormat>BA-{0000}</displayFormat>
        <label>BoredActivity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BoredActivitys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BoredActivity__c/fields/Accessibilty__c.field-meta.xml
<CustomField>
    <fullName>Accessibilty__c</fullName>
    <label>Accessibilty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BoredActivity__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BoredActivity__c/fields/Participants__c.field-meta.xml
<CustomField>
    <fullName>Participants__c</fullName>
    <label>Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BoredActivity.cls
public class BoredActivity {
    public static void boredActivityMethod(){
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        req.setEndpoint('https://www.boredapi.com/api/activity');
        
        HttpResponse res = h.send(req);
        system.debug('Response:'+res);
        integer statusCode = res.getStatusCode();
        system.debug('StatusCode:'+statusCode);
        string body = res.getBody();
        system.debug('the body:'+body);
        BoredActivityInner bai = (BoredActivityInner)JSON.deserialize(body,BoredActivityInner.class);
        system.debug('boredActivity-->'+bai);
        storeBoredActivity(bai);
        
    }
    public static void storeBoredActivity(BoredActivityInner bar){
        BoredActivity__c ba = new BoredActivity__c();
        ba.Activity__c = bar.activity;
        ba.Type__c = bar.types;
        ba.Participants__c = bar.participants;
        ba.Price__c = bar.price;
        ba.Link__c = bar.link;
        ba.Key__c = bar.key;
        ba.Accessibilty__c = bar.access;
        insert ba;
       }
    public class BoredActivityInner{
        public string activity;
        public string types;
        public decimal participants;
        public decimal price;
        public string link;
        public string key;
        public decimal access;
    }
}