force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/FatherName__c.field-meta.xml
<CustomField>
    <fullName>FatherName__c</fullName>
    <label>FatherName</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Maths__c.field-meta.xml
<CustomField>
    <fullName>Maths__c</fullName>
    <label>Maths</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Overall_Result__c.field-meta.xml
<CustomField>
    <fullName>Overall_Result__c</fullName>
    <label>Overall Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Result_Class__c.field-meta.xml
<CustomField>
    <fullName>Result_Class__c</fullName>
    <label>Result Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Distinction</fullName>
            </value>
            <value>
                <fullName>First Class</fullName>
            </value>
            <value>
                <fullName>Second Class</fullName>
            </value>
            <value>
                <fullName>Third Class</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Science__c.field-meta.xml
<CustomField>
    <fullName>Science__c</fullName>
    <label>Science</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Social_Science__c.field-meta.xml
<CustomField>
    <fullName>Social_Science__c</fullName>
    <label>Social Science</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Total_Mark__c.field-meta.xml
<CustomField>
    <fullName>Total_Mark__c</fullName>
    <label>Total Mark</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/StudentServiceController.cls
public without sharing class StudentServiceController {
    /*@AuraEnabled
    public static Student__c createStudentRecord(Student__c newRecord){
        
        insert newRecord;
        return newRecord;
        
    }*/
    
    @AuraEnabled
    public static List<Student__c>  studentlist(String name, String fathersName,Decimal tamil,Decimal english,Decimal maths,Decimal science,Decimal social) {
        Student__c stud = new Student__c() ;
        List<Student__c> studList = new List<Student__c>();    
        stud.Name = name;
        stud.FatherName__c = fathersName;
        stud.Language__c = tamil;
        stud.English__c = english;
        stud.Maths__c = maths;
        stud.Science__c = science;
        stud.Social_Science__c = social;
        
        stud.Total_Mark__c = stud.Language__c+ stud.English__c+ stud.Maths__c+ stud.Science__c+ stud.Social_Science__c;
        Decimal avg = ( stud.Language__c+ stud.English__c+ stud.Maths__c+ stud.Science__c+ stud.Social_Science__c)/5;
        stud.Percentage__c = avg;
        
        
        if(avg > 75){
            stud.Result_Class__c = 'Distinction';
        }else if (avg >= 60 && avg <= 75){
            stud.Result_Class__c = 'First Class';
        }else if ( avg > 50 && avg <= 60){
            stud.Result_Class__c = 'Second Class';
        }
        else if ( avg > 40 && avg <= 50){
            stud.Result_Class__c = 'Third Class';
        }
        
        if(stud.Language__c >40 && stud.English__c > 40 && stud.Maths__c >40 && stud.Science__c > 40 && stud.Social_Science__c > 40){
            stud.Overall_Result__c = 'Pass'; 
        }
        else{
            stud.Overall_Result__c = 'Fail';
        }
        studList.add(stud);
        try {
            insert studList;
            System.debug('@@@@@@ Student record created @@@@ '+studList);
        }catch(Exception e) {
            return  null;
        }
        return studList;
    }
}