force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Maths__c.field-meta.xml
<CustomField>
    <fullName>Maths__c</fullName>
    <label>Maths</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Science__c.field-meta.xml
<CustomField>
    <fullName>Science__c</fullName>
    <label>Science</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Social_Science__c.field-meta.xml
<CustomField>
    <fullName>Social_Science__c</fullName>
    <label>Social Science</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Total_Mark__c.field-meta.xml
<CustomField>
    <fullName>Total_Mark__c</fullName>
    <label>Total Mark</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/StudentResultManagement.cls
public with sharing class StudentResultManagement
{
    @AuraEnabled
    public static Student__c createStudentRecord(Student__c newRecord){
        List<Student__c> stuList = new List<Student__c>();
        try{
            if(newRecord != null)
            {
                newRecord.Total_Mark__c = newRecord.Language__c+
                    newRecord.English__c+
                    newRecord.Maths__c+
                    newRecord.Science__c+
                    newRecord.Social_Science__c;
                newRecord.Percentage__c = (newRecord.Language__c+
                                           newRecord.English__c+
                                           newRecord.Maths__c+
                                           newRecord.Science__c+
                                           newRecord.Social_Science__c)/5;
                stuList.add(newRecord); 
                insert stuList;
            }
            
            return newRecord;
        }
        catch (Exception e)
        {
            System.debug(e.getMessage());
        }
        return newRecord;
    }
}