force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>bca</fullName>
            </value>
            <value>
                <fullName>cs</fullName>
            </value>
            <value>
                <fullName>bcom</fullName>
            </value>
            <value>
                <fullName>bba</fullName>
            </value>
            <value>
                <fullName>mba</fullName>
            </value>
            <value>
                <fullName>mca</fullName>
            </value>
            <value>
                <fullName>msc</fullName>
            </value>
            <value>
                <fullName>bsc</fullName>
            </value>
            <value>
                <fullName>ba</fullName>
            </value>
            <value>
                <fullName>ma</fullName>
            </value>
            <value>
                <fullName>msw</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/FatherName__c.field-meta.xml
<CustomField>
    <fullName>FatherName__c</fullName>
    <label>FatherName</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/MotherName__c.field-meta.xml
<CustomField>
    <fullName>MotherName__c</fullName>
    <label>MotherName</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <label>PhoneNumber</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Shoe_Design__c.field-meta.xml
<CustomField>
    <fullName>Shoe_Design__c</fullName>
    <label>Shoe Design</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>orange</fullName>
            </value>
            <value>
                <fullName>green</fullName>
            </value>
            <value>
                <fullName>yellow</fullName>
            </value>
            <value>
                <fullName>red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/studentInfoHandler.cls
public class studentInfoHandler 
{
    @AuraEnabled
public static void studentInfoMethod(Student__c studobj)
{
    
    system.debug('Student__c:'+studobj.Name);
    system.debug('Student__c'+studobj.FatherName__c);
    system.debug('Student__c'+studobj.MotherName__c);
    system.debug('Student__c'+studobj.PhoneNumber__c);
    system.debug('Student__c'+studobj.Department__c);
    system.debug('Student__c'+studobj.Shoe_Design__c);
    insert studobj;
}
    @AuraEnabled
    public static List <String> getPicklistValues(sObject objectVar, String fieldNameVar) {
         System.debug('obj '+objectVar);
        List <String> pList = new list <String>();
       
        //Get the object type of the SObject.
        Schema.sObjectType objType = objectVar.getSObjectType();
 
        //Describe the SObject using its object type.
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
 
        //Get a map of fields for the SObject
        Map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
 
        //Get the list of picklist values for this field.
        List<Schema.PicklistEntry > values = fieldMap.get(fieldNameVar).getDescribe().getPickListValues();
 
        //Add these values to the selectoption list.
        for (Schema.PicklistEntry a: values) {
            pList.add(a.getValue());
        }
        
        system.debug('pList '+pList);
        return pList;
    }
    @AuraEnabled
    public static List<Student__c> retrievestudentinfo()
    {
        return[select Name,FatherName__c,MotherName__c,PhoneNumber__c from Student__c order by createdDate ASC];
    }
    
        
}