force-app/main/default/objects/ParentObj__c/ParentObj__c.object-meta.xml
<CustomObject>
    <label>ParentObj</label>
    <nameField>
        <label>Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ParentsObjs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ParentObj__c/fields/Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Number__c</fullName>
    <label>Aadhar Number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParentObj__c/fields/Job_Sector__c.field-meta.xml
<CustomField>
    <fullName>Job_Sector__c</fullName>
    <label>Job Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Govt</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>UnEmployee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ParentObj__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StudentObj__c/StudentObj__c.object-meta.xml
<CustomObject>
    <label>StudentObj</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StudentObjs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentObj__c/fields/Discount_Requested__c.field-meta.xml
<CustomField>
    <fullName>Discount_Requested__c</fullName>
    <label>Discount Requested</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/StudentObj__c/fields/Father_Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Father_Aadhar_Number__c</fullName>
    <label>Father Aadhar Number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StudentObj__c/fields/Mother_Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Mother_Aadhar_Number__c</fullName>
    <label>Mother Aadhar Number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/StudentPageController.cls
public with sharing class StudentPageController {
    public StudentObj__c newStudentObject {get;set;}
    public ParentObj__c motherRecord {get;set;}
    public ParentObj__c fatherRecord {get;set;}
    public Decimal motherAdhaarNumber {get;set;}
    public Decimal fatherAdhaarNumber {get;set;}
    public String motherOccupation {get;set;}
    public String fatherOccupation {get;set;}
    public Boolean bothParentsAdharNumberWrong {get;set;}
    public Boolean fatherInformationMissing {get;set;}
    public Boolean motherInformationMissing  {get;set;}
    
    public StudentPageController(ApexPages.StandardController controller) {
        intVariables();
        newStudentObject.Name = '';
        newStudentObject.Aadhar_number__c = 0;
        newStudentObject.Mother_Aadhar_Number__c = 0;
        newStudentObject.Father_Aadhar_number__c = 0;
        newStudentObject.Discount_Requested__c = 0;
    }
    
    private void intVariables() {
        bothParentsAdharNumberWrong = false;
        
        fatherInformationMissing = false;
        motherInformationMissing = false;
        newStudentObject = new 	StudentObj__c();
        
    }
    
    public PageReference saveRecord() {
        try {
            Boolean isDataValid = isDataValidForDiscount();
            System.debug('Parent Adhaar Error value'+bothParentsAdharNumberWrong);
            if(isDataValid) {
                insert newStudentObject;
            }
            else {
                if(bothParentsAdharNumberWrong) {
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,  'Adhaar Info of Parents not matching '+newStudentObject.Name));  
                } 
                if(motherInformationMissing) {
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Mother Information Incorrect'+newStudentObject.Name));  
                }
                if(fatherInformationMissing) {
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Father Information Incorrect'+newStudentObject.Name));  
                }
                
            }
            
        }catch(Exception e) {
            System.debug('The Exception is at Stack Trace'+e.getStackTraceString());
            System.debug('The Exception is at Line Number'+e.getLineNumber());
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, e.getMessage(), 'Error Saving the Record @Saravana...please check'));  
        }
        return NULL; 
    }
    
    private Boolean isDataValidForDiscount() {
        motherAdhaarNumber = newStudentObject.Mother_Aadhar_Number__c;
        fatherAdhaarNumber = newStudentObject.Father_Aadhar_number__c;
        
        System.debug('motherAdhaarNumber --> '+motherAdhaarNumber);
        System.debug('fatherAdhaarNumber --> '+fatherAdhaarNumber);
        
        
        List<ParentObj__c> parentRecords = [select Id , 
                                            Aadhar_Number__c, 
                                            Name, 
                                            Job_Sector__c,
                                            Relationship__c
                                            from ParentObj__c 
                                            where Aadhar_Number__c 
                                            IN (:motherAdhaarNumber, :fatherAdhaarNumber)];
        
        System.debug('Parent Records  --> '+parentRecords);
        if(parentRecords.size() == 0) {
            bothParentsAdharNumberWrong = true;
            return false;
            
        }
        for(ParentObj__c parent : parentRecords) {
            if(parent.Relationship__c.equalsIgnoreCase('Father')) {
                this.fatherRecord = parent;
            }
            if(parent.Relationship__c.equalsIgnoreCase('Mother')) {
                this.motherRecord = parent;
            }
        }
        System.debug('this.fatherRecord --> '+this.fatherRecord);
        System.debug('this.motherRecord --> '+this.fatherRecord);
        
        if(fatherRecord==NULL){
            fatherInformationMissing = true;
            return false;
        }
        
        if(motherRecord==NULL){
            motherInformationMissing = true;
            return false;
        }
        
        this.fatherOccupation = fatherRecord.Job_Sector__c;
        this.motherOccupation = motherRecord.Job_Sector__c;
        
        //Condition 1 - If Father Job is Govt, Mother Job is Govt maximum Discount = 5%
        
        System.debug('this.fatherOccupation --> '+this.fatherOccupation);
        System.debug('this.motherOccupation --> '+this.motherOccupation);
        System.debug('this.newStudentObject --> '+this.newStudentObject);
        System.debug('this.newStudentObject.Discount_Requested__c --> '+this.newStudentObject.Discount_Requested__c);
        
        if(this.fatherOccupation.equalsIgnoreCase('Govt') && 
           this.motherOccupation.equalsIgnoreCase('Govt') &&
           this.newStudentObject.Discount_Requested__c > 5)  {
               return false;
           }
        
        //Condition 2 - If Father Job is Govt, Mother Job is Private  maximum Discount = 10%
        
        
        
        if(this.fatherOccupation.equalsIgnoreCase('Govt') && 
           this.motherOccupation.equalsIgnoreCase('Private') &&
           this.newStudentObject.Discount_Requested__c > 10)  {
               return false;
           }
        
        //Condition 3 - If Father Job is Private, Mother Job is Private maximum Discount = 30%
        
        
        
        if(this.fatherOccupation.equalsIgnoreCase('Private') && 
           this.motherOccupation.equalsIgnoreCase('Private') &&
           this.newStudentObject.Discount_Requested__c > 30)  {
               return false;
           }
        
        
        //Condition 4 - If Father and mother are Unemployed maximum Discount = 80%
        
        
        
        if(this.fatherOccupation.equalsIgnoreCase('Unemployee') && 
           this.motherOccupation.equalsIgnoreCase('Unemployee') &&
           this.newStudentObject.Discount_Requested__c > 80)  {
               return false;
           }
        return true;
    }
}